language: cpp

notifications:
  email: false

sudo: required
dist: xenial

branches:
  only:
    - master
    - B3_0_Release

addons:
  apt:
    packages:
    - libtommath0
    - libtommath-dev
    - libtomcrypt0
    - libtomcrypt-dev
    - libicu-dev
    - zlib1g-dev

script:
  - ./autogen.sh --enable-binreloc --prefix=/opt/firebird
  - make
  # make dist
  # tar xzvf gen/Firebird-[0-9]*.tar.gz
  # (cd Firebird-[0-9]*; sudo ./install.sh -silent)
  # sudo usermod -a -G firebird travis
