language: cpp

notifications:
  email: false

sudo: required
dist: xenial

branches:
  only:
    - master
    - B3_0_Release

addons:
  apt:
    packages:
    - libtool-bin
    - libtommath0
    - libtommath-dev
    - libicu-dev
    - zlib1g-dev

script:
  - ./autogen.sh --enable-binreloc --with-builtin-tomcrypt --prefix=/opt/firebird
  - make
  - make dist
  - tar xzvf gen/Firebird-[0-9]*.tar.gz
  - (cd Firebird-[0-9]*; sudo ./install.sh -silent)
