name: CI-alpine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine
    
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Prepare
        run: apk update && apk --no-cache --update add build-base libtool git autoconf automake zlib-dev icu-dev ncurses-dev libedit-dev linux-headers tar

      - name: Build
        run: |
          ./autogen.sh --enable-binreloc-threads --with-builtin-tomcrypt -with-builtin-tommath --prefix=/opt/firebird
          make -j4
          make dist
          tar xzvf gen/Firebird-[0-9]*.tar.gz
      
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: firebird-linux-alpine
          path: gen/Firebird-[0-9]*.tar.gz
