name: tzdata-update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  tzdata-update:
    if: github.repository == 'FirebirdSQL/firebird'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - v5.0-release
          - v4.0-release

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Download ICU
        run: |
          wget --no-verbose -O /tmp/icu.zip https://github.com/unicode-org/icu-data/archive/refs/heads/main.zip
          unzip -d /tmp /tmp/icu.zip

      - name: Check and update
        run: |
          VERSION=`ls /tmp/icu-data-main/tzdata/icunew/ -r1a |head -1`
          echo Last version: $VERSION

          if [ "$VERSION" == "`cat extern/icu/tzdata/version.txt`" ]
          then
            exit
          fi

          echo $VERSION > extern/icu/tzdata/version.txt
          extern/icu/tzdata/update.sh
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update tzdata to version ${{ env.VERSION }}.
          title: Update tzdata to version ${{ env.VERSION }}.
          assignees: asfernandes
          branch: work/tzdata-update-${{ matrix.branch }}
          base: ${{ matrix.branch }}
          labels: |
            type: task
